import type { Metadata } from "next";

import "../styles/globals.css";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Swipe & Watch",
  description: "Generated by create next app",
};

export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white antialiased`}>
        {children}
      </body>
    </html>
  );
}
